# Generated by Django 3.2.4 on 2024-10-23 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
