# Generated by Django 3.2.4 on 2024-11-04 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20241023_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='draw',
            name='requested_by',
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=models.CASCADE,
                related_name='draws',
                default=1  # Replace `1` with the ID of a valid user in your database
            ),
            preserve_default=False,
        ),
    ]
